from __future__ import annotations
import atexit as atexit
from functools import wraps
from itertools import chain
from pandas.core.series import Series as _pd_Series
from talib._ta_lib import ACOS
from talib._ta_lib import AD
from talib._ta_lib import ADD
from talib._ta_lib import ADOSC
from talib._ta_lib import ADX
from talib._ta_lib import ADXR
from talib._ta_lib import APO
from talib._ta_lib import AROON
from talib._ta_lib import AROONOSC
from talib._ta_lib import ASIN
from talib._ta_lib import ATAN
from talib._ta_lib import ATR
from talib._ta_lib import AVGPRICE
from talib._ta_lib import BBANDS
from talib._ta_lib import BETA
from talib._ta_lib import BOP
from talib._ta_lib import CCI
from talib._ta_lib import CDL2CROWS
from talib._ta_lib import CDL3BLACKCROWS
from talib._ta_lib import CDL3INSIDE
from talib._ta_lib import CDL3LINESTRIKE
from talib._ta_lib import CDL3OUTSIDE
from talib._ta_lib import CDL3STARSINSOUTH
from talib._ta_lib import CDL3WHITESOLDIERS
from talib._ta_lib import CDLABANDONEDBABY
from talib._ta_lib import CDLADVANCEBLOCK
from talib._ta_lib import CDLBELTHOLD
from talib._ta_lib import CDLBREAKAWAY
from talib._ta_lib import CDLCLOSINGMARUBOZU
from talib._ta_lib import CDLCONCEALBABYSWALL
from talib._ta_lib import CDLCOUNTERATTACK
from talib._ta_lib import CDLDARKCLOUDCOVER
from talib._ta_lib import CDLDOJI
from talib._ta_lib import CDLDOJISTAR
from talib._ta_lib import CDLDRAGONFLYDOJI
from talib._ta_lib import CDLENGULFING
from talib._ta_lib import CDLEVENINGDOJISTAR
from talib._ta_lib import CDLEVENINGSTAR
from talib._ta_lib import CDLGAPSIDESIDEWHITE
from talib._ta_lib import CDLGRAVESTONEDOJI
from talib._ta_lib import CDLHAMMER
from talib._ta_lib import CDLHANGINGMAN
from talib._ta_lib import CDLHARAMI
from talib._ta_lib import CDLHARAMICROSS
from talib._ta_lib import CDLHIGHWAVE
from talib._ta_lib import CDLHIKKAKE
from talib._ta_lib import CDLHIKKAKEMOD
from talib._ta_lib import CDLHOMINGPIGEON
from talib._ta_lib import CDLIDENTICAL3CROWS
from talib._ta_lib import CDLINNECK
from talib._ta_lib import CDLINVERTEDHAMMER
from talib._ta_lib import CDLKICKING
from talib._ta_lib import CDLKICKINGBYLENGTH
from talib._ta_lib import CDLLADDERBOTTOM
from talib._ta_lib import CDLLONGLEGGEDDOJI
from talib._ta_lib import CDLLONGLINE
from talib._ta_lib import CDLMARUBOZU
from talib._ta_lib import CDLMATCHINGLOW
from talib._ta_lib import CDLMATHOLD
from talib._ta_lib import CDLMORNINGDOJISTAR
from talib._ta_lib import CDLMORNINGSTAR
from talib._ta_lib import CDLONNECK
from talib._ta_lib import CDLPIERCING
from talib._ta_lib import CDLRICKSHAWMAN
from talib._ta_lib import CDLRISEFALL3METHODS
from talib._ta_lib import CDLSEPARATINGLINES
from talib._ta_lib import CDLSHOOTINGSTAR
from talib._ta_lib import CDLSHORTLINE
from talib._ta_lib import CDLSPINNINGTOP
from talib._ta_lib import CDLSTALLEDPATTERN
from talib._ta_lib import CDLSTICKSANDWICH
from talib._ta_lib import CDLTAKURI
from talib._ta_lib import CDLTASUKIGAP
from talib._ta_lib import CDLTHRUSTING
from talib._ta_lib import CDLTRISTAR
from talib._ta_lib import CDLUNIQUE3RIVER
from talib._ta_lib import CDLUPSIDEGAP2CROWS
from talib._ta_lib import CDLXSIDEGAP3METHODS
from talib._ta_lib import CEIL
from talib._ta_lib import CMO
from talib._ta_lib import CORREL
from talib._ta_lib import COS
from talib._ta_lib import COSH
from talib._ta_lib import DEMA
from talib._ta_lib import DIV
from talib._ta_lib import DX
from talib._ta_lib import EMA
from talib._ta_lib import EXP
from talib._ta_lib import FLOOR
from talib._ta_lib import HT_DCPERIOD
from talib._ta_lib import HT_DCPHASE
from talib._ta_lib import HT_PHASOR
from talib._ta_lib import HT_SINE
from talib._ta_lib import HT_TRENDLINE
from talib._ta_lib import HT_TRENDMODE
from talib._ta_lib import KAMA
from talib._ta_lib import LINEARREG
from talib._ta_lib import LINEARREG_ANGLE
from talib._ta_lib import LINEARREG_INTERCEPT
from talib._ta_lib import LINEARREG_SLOPE
from talib._ta_lib import LN
from talib._ta_lib import LOG10
from talib._ta_lib import MA
from talib._ta_lib import MACD
from talib._ta_lib import MACDEXT
from talib._ta_lib import MACDFIX
from talib._ta_lib import MAMA
from talib._ta_lib import MAVP
from talib._ta_lib import MAX
from talib._ta_lib import MAXINDEX
from talib._ta_lib import MEDPRICE
from talib._ta_lib import MFI
from talib._ta_lib import MIDPOINT
from talib._ta_lib import MIDPRICE
from talib._ta_lib import MIN
from talib._ta_lib import MININDEX
from talib._ta_lib import MINMAX
from talib._ta_lib import MINMAXINDEX
from talib._ta_lib import MINUS_DI
from talib._ta_lib import MINUS_DM
from talib._ta_lib import MOM
from talib._ta_lib import MULT
from talib._ta_lib import NATR
from talib._ta_lib import OBV
from talib._ta_lib import PLUS_DI
from talib._ta_lib import PLUS_DM
from talib._ta_lib import PPO
from talib._ta_lib import ROC
from talib._ta_lib import ROCP
from talib._ta_lib import ROCR
from talib._ta_lib import ROCR100
from talib._ta_lib import RSI
from talib._ta_lib import SAR
from talib._ta_lib import SAREXT
from talib._ta_lib import SIN
from talib._ta_lib import SINH
from talib._ta_lib import SMA
from talib._ta_lib import SQRT
from talib._ta_lib import STDDEV
from talib._ta_lib import STOCH
from talib._ta_lib import STOCHF
from talib._ta_lib import STOCHRSI
from talib._ta_lib import SUB
from talib._ta_lib import SUM
from talib._ta_lib import T3
from talib._ta_lib import TAN
from talib._ta_lib import TANH
from talib._ta_lib import TEMA
from talib._ta_lib import TRANGE
from talib._ta_lib import TRIMA
from talib._ta_lib import TRIX
from talib._ta_lib import TSF
from talib._ta_lib import TYPPRICE
from talib._ta_lib import ULTOSC
from talib._ta_lib import VAR
from talib._ta_lib import WCLPRICE
from talib._ta_lib import WILLR
from talib._ta_lib import WMA
from talib._ta_lib import _ta_get_compatibility as get_compatibility
from talib._ta_lib import _ta_get_unstable_period as get_unstable_period
from talib._ta_lib import _ta_initialize
from talib._ta_lib import _ta_set_compatibility as set_compatibility
from talib._ta_lib import _ta_set_unstable_period as set_unstable_period
from talib._ta_lib import _ta_shutdown
from talib._ta_lib import stream_ACOS
from talib._ta_lib import stream_AD
from talib._ta_lib import stream_ADD
from talib._ta_lib import stream_ADOSC
from talib._ta_lib import stream_ADX
from talib._ta_lib import stream_ADXR
from talib._ta_lib import stream_APO
from talib._ta_lib import stream_AROON
from talib._ta_lib import stream_AROONOSC
from talib._ta_lib import stream_ASIN
from talib._ta_lib import stream_ATAN
from talib._ta_lib import stream_ATR
from talib._ta_lib import stream_AVGPRICE
from talib._ta_lib import stream_BBANDS
from talib._ta_lib import stream_BETA
from talib._ta_lib import stream_BOP
from talib._ta_lib import stream_CCI
from talib._ta_lib import stream_CDL2CROWS
from talib._ta_lib import stream_CDL3BLACKCROWS
from talib._ta_lib import stream_CDL3INSIDE
from talib._ta_lib import stream_CDL3LINESTRIKE
from talib._ta_lib import stream_CDL3OUTSIDE
from talib._ta_lib import stream_CDL3STARSINSOUTH
from talib._ta_lib import stream_CDL3WHITESOLDIERS
from talib._ta_lib import stream_CDLABANDONEDBABY
from talib._ta_lib import stream_CDLADVANCEBLOCK
from talib._ta_lib import stream_CDLBELTHOLD
from talib._ta_lib import stream_CDLBREAKAWAY
from talib._ta_lib import stream_CDLCLOSINGMARUBOZU
from talib._ta_lib import stream_CDLCONCEALBABYSWALL
from talib._ta_lib import stream_CDLCOUNTERATTACK
from talib._ta_lib import stream_CDLDARKCLOUDCOVER
from talib._ta_lib import stream_CDLDOJI
from talib._ta_lib import stream_CDLDOJISTAR
from talib._ta_lib import stream_CDLDRAGONFLYDOJI
from talib._ta_lib import stream_CDLENGULFING
from talib._ta_lib import stream_CDLEVENINGDOJISTAR
from talib._ta_lib import stream_CDLEVENINGSTAR
from talib._ta_lib import stream_CDLGAPSIDESIDEWHITE
from talib._ta_lib import stream_CDLGRAVESTONEDOJI
from talib._ta_lib import stream_CDLHAMMER
from talib._ta_lib import stream_CDLHANGINGMAN
from talib._ta_lib import stream_CDLHARAMI
from talib._ta_lib import stream_CDLHARAMICROSS
from talib._ta_lib import stream_CDLHIGHWAVE
from talib._ta_lib import stream_CDLHIKKAKE
from talib._ta_lib import stream_CDLHIKKAKEMOD
from talib._ta_lib import stream_CDLHOMINGPIGEON
from talib._ta_lib import stream_CDLIDENTICAL3CROWS
from talib._ta_lib import stream_CDLINNECK
from talib._ta_lib import stream_CDLINVERTEDHAMMER
from talib._ta_lib import stream_CDLKICKING
from talib._ta_lib import stream_CDLKICKINGBYLENGTH
from talib._ta_lib import stream_CDLLADDERBOTTOM
from talib._ta_lib import stream_CDLLONGLEGGEDDOJI
from talib._ta_lib import stream_CDLLONGLINE
from talib._ta_lib import stream_CDLMARUBOZU
from talib._ta_lib import stream_CDLMATCHINGLOW
from talib._ta_lib import stream_CDLMATHOLD
from talib._ta_lib import stream_CDLMORNINGDOJISTAR
from talib._ta_lib import stream_CDLMORNINGSTAR
from talib._ta_lib import stream_CDLONNECK
from talib._ta_lib import stream_CDLPIERCING
from talib._ta_lib import stream_CDLRICKSHAWMAN
from talib._ta_lib import stream_CDLRISEFALL3METHODS
from talib._ta_lib import stream_CDLSEPARATINGLINES
from talib._ta_lib import stream_CDLSHOOTINGSTAR
from talib._ta_lib import stream_CDLSHORTLINE
from talib._ta_lib import stream_CDLSPINNINGTOP
from talib._ta_lib import stream_CDLSTALLEDPATTERN
from talib._ta_lib import stream_CDLSTICKSANDWICH
from talib._ta_lib import stream_CDLTAKURI
from talib._ta_lib import stream_CDLTASUKIGAP
from talib._ta_lib import stream_CDLTHRUSTING
from talib._ta_lib import stream_CDLTRISTAR
from talib._ta_lib import stream_CDLUNIQUE3RIVER
from talib._ta_lib import stream_CDLUPSIDEGAP2CROWS
from talib._ta_lib import stream_CDLXSIDEGAP3METHODS
from talib._ta_lib import stream_CEIL
from talib._ta_lib import stream_CMO
from talib._ta_lib import stream_CORREL
from talib._ta_lib import stream_COS
from talib._ta_lib import stream_COSH
from talib._ta_lib import stream_DEMA
from talib._ta_lib import stream_DIV
from talib._ta_lib import stream_DX
from talib._ta_lib import stream_EMA
from talib._ta_lib import stream_EXP
from talib._ta_lib import stream_FLOOR
from talib._ta_lib import stream_HT_DCPERIOD
from talib._ta_lib import stream_HT_DCPHASE
from talib._ta_lib import stream_HT_PHASOR
from talib._ta_lib import stream_HT_SINE
from talib._ta_lib import stream_HT_TRENDLINE
from talib._ta_lib import stream_HT_TRENDMODE
from talib._ta_lib import stream_KAMA
from talib._ta_lib import stream_LINEARREG
from talib._ta_lib import stream_LINEARREG_ANGLE
from talib._ta_lib import stream_LINEARREG_INTERCEPT
from talib._ta_lib import stream_LINEARREG_SLOPE
from talib._ta_lib import stream_LN
from talib._ta_lib import stream_LOG10
from talib._ta_lib import stream_MA
from talib._ta_lib import stream_MACD
from talib._ta_lib import stream_MACDEXT
from talib._ta_lib import stream_MACDFIX
from talib._ta_lib import stream_MAMA
from talib._ta_lib import stream_MAVP
from talib._ta_lib import stream_MAX
from talib._ta_lib import stream_MAXINDEX
from talib._ta_lib import stream_MEDPRICE
from talib._ta_lib import stream_MFI
from talib._ta_lib import stream_MIDPOINT
from talib._ta_lib import stream_MIDPRICE
from talib._ta_lib import stream_MIN
from talib._ta_lib import stream_MININDEX
from talib._ta_lib import stream_MINMAX
from talib._ta_lib import stream_MINMAXINDEX
from talib._ta_lib import stream_MINUS_DI
from talib._ta_lib import stream_MINUS_DM
from talib._ta_lib import stream_MOM
from talib._ta_lib import stream_MULT
from talib._ta_lib import stream_NATR
from talib._ta_lib import stream_OBV
from talib._ta_lib import stream_PLUS_DI
from talib._ta_lib import stream_PLUS_DM
from talib._ta_lib import stream_PPO
from talib._ta_lib import stream_ROC
from talib._ta_lib import stream_ROCP
from talib._ta_lib import stream_ROCR
from talib._ta_lib import stream_ROCR100
from talib._ta_lib import stream_RSI
from talib._ta_lib import stream_SAR
from talib._ta_lib import stream_SAREXT
from talib._ta_lib import stream_SIN
from talib._ta_lib import stream_SINH
from talib._ta_lib import stream_SMA
from talib._ta_lib import stream_SQRT
from talib._ta_lib import stream_STDDEV
from talib._ta_lib import stream_STOCH
from talib._ta_lib import stream_STOCHF
from talib._ta_lib import stream_STOCHRSI
from talib._ta_lib import stream_SUB
from talib._ta_lib import stream_SUM
from talib._ta_lib import stream_T3
from talib._ta_lib import stream_TAN
from talib._ta_lib import stream_TANH
from talib._ta_lib import stream_TEMA
from talib._ta_lib import stream_TRANGE
from talib._ta_lib import stream_TRIMA
from talib._ta_lib import stream_TRIX
from talib._ta_lib import stream_TSF
from talib._ta_lib import stream_TYPPRICE
from talib._ta_lib import stream_ULTOSC
from talib._ta_lib import stream_VAR
from talib._ta_lib import stream_WCLPRICE
from talib._ta_lib import stream_WILLR
from talib._ta_lib import stream_WMA
from talib._ta_lib import stream_WMA as wrapped_func
from . import _ta_lib
from . import stream
__all__: list = ['get_functions', 'get_function_groups', 'ACOS', 'AD', 'ADD', 'ADOSC', 'ADX', 'ADXR', 'APO', 'AROON', 'AROONOSC', 'ASIN', 'ATAN', 'ATR', 'AVGPRICE', 'BBANDS', 'BETA', 'BOP', 'CCI', 'CDL2CROWS', 'CDL3BLACKCROWS', 'CDL3INSIDE', 'CDL3LINESTRIKE', 'CDL3OUTSIDE', 'CDL3STARSINSOUTH', 'CDL3WHITESOLDIERS', 'CDLABANDONEDBABY', 'CDLADVANCEBLOCK', 'CDLBELTHOLD', 'CDLBREAKAWAY', 'CDLCLOSINGMARUBOZU', 'CDLCONCEALBABYSWALL', 'CDLCOUNTERATTACK', 'CDLDARKCLOUDCOVER', 'CDLDOJI', 'CDLDOJISTAR', 'CDLDRAGONFLYDOJI', 'CDLENGULFING', 'CDLEVENINGDOJISTAR', 'CDLEVENINGSTAR', 'CDLGAPSIDESIDEWHITE', 'CDLGRAVESTONEDOJI', 'CDLHAMMER', 'CDLHANGINGMAN', 'CDLHARAMI', 'CDLHARAMICROSS', 'CDLHIGHWAVE', 'CDLHIKKAKE', 'CDLHIKKAKEMOD', 'CDLHOMINGPIGEON', 'CDLIDENTICAL3CROWS', 'CDLINNECK', 'CDLINVERTEDHAMMER', 'CDLKICKING', 'CDLKICKINGBYLENGTH', 'CDLLADDERBOTTOM', 'CDLLONGLEGGEDDOJI', 'CDLLONGLINE', 'CDLMARUBOZU', 'CDLMATCHINGLOW', 'CDLMATHOLD', 'CDLMORNINGDOJISTAR', 'CDLMORNINGSTAR', 'CDLONNECK', 'CDLPIERCING', 'CDLRICKSHAWMAN', 'CDLRISEFALL3METHODS', 'CDLSEPARATINGLINES', 'CDLSHOOTINGSTAR', 'CDLSHORTLINE', 'CDLSPINNINGTOP', 'CDLSTALLEDPATTERN', 'CDLSTICKSANDWICH', 'CDLTAKURI', 'CDLTASUKIGAP', 'CDLTHRUSTING', 'CDLTRISTAR', 'CDLUNIQUE3RIVER', 'CDLUPSIDEGAP2CROWS', 'CDLXSIDEGAP3METHODS', 'CEIL', 'CMO', 'CORREL', 'COS', 'COSH', 'DEMA', 'DIV', 'DX', 'EMA', 'EXP', 'FLOOR', 'HT_DCPERIOD', 'HT_DCPHASE', 'HT_PHASOR', 'HT_SINE', 'HT_TRENDLINE', 'HT_TRENDMODE', 'KAMA', 'LINEARREG', 'LINEARREG_ANGLE', 'LINEARREG_INTERCEPT', 'LINEARREG_SLOPE', 'LN', 'LOG10', 'MA', 'MACD', 'MACDEXT', 'MACDFIX', 'MAMA', 'MAVP', 'MAX', 'MAXINDEX', 'MEDPRICE', 'MFI', 'MIDPOINT', 'MIDPRICE', 'MIN', 'MININDEX', 'MINMAX', 'MINMAXINDEX', 'MINUS_DI', 'MINUS_DM', 'MOM', 'MULT', 'NATR', 'OBV', 'PLUS_DI', 'PLUS_DM', 'PPO', 'ROC', 'ROCP', 'ROCR', 'ROCR100', 'RSI', 'SAR', 'SAREXT', 'SIN', 'SINH', 'SMA', 'SQRT', 'STDDEV', 'STOCH', 'STOCHF', 'STOCHRSI', 'SUB', 'SUM', 'T3', 'TAN', 'TANH', 'TEMA', 'TRANGE', 'TRIMA', 'TRIX', 'TSF', 'TYPPRICE', 'ULTOSC', 'VAR', 'WCLPRICE', 'WILLR', 'WMA', 'stream_ACOS', 'stream_AD', 'stream_ADD', 'stream_ADOSC', 'stream_ADX', 'stream_ADXR', 'stream_APO', 'stream_AROON', 'stream_AROONOSC', 'stream_ASIN', 'stream_ATAN', 'stream_ATR', 'stream_AVGPRICE', 'stream_BBANDS', 'stream_BETA', 'stream_BOP', 'stream_CCI', 'stream_CDL2CROWS', 'stream_CDL3BLACKCROWS', 'stream_CDL3INSIDE', 'stream_CDL3LINESTRIKE', 'stream_CDL3OUTSIDE', 'stream_CDL3STARSINSOUTH', 'stream_CDL3WHITESOLDIERS', 'stream_CDLABANDONEDBABY', 'stream_CDLADVANCEBLOCK', 'stream_CDLBELTHOLD', 'stream_CDLBREAKAWAY', 'stream_CDLCLOSINGMARUBOZU', 'stream_CDLCONCEALBABYSWALL', 'stream_CDLCOUNTERATTACK', 'stream_CDLDARKCLOUDCOVER', 'stream_CDLDOJI', 'stream_CDLDOJISTAR', 'stream_CDLDRAGONFLYDOJI', 'stream_CDLENGULFING', 'stream_CDLEVENINGDOJISTAR', 'stream_CDLEVENINGSTAR', 'stream_CDLGAPSIDESIDEWHITE', 'stream_CDLGRAVESTONEDOJI', 'stream_CDLHAMMER', 'stream_CDLHANGINGMAN', 'stream_CDLHARAMI', 'stream_CDLHARAMICROSS', 'stream_CDLHIGHWAVE', 'stream_CDLHIKKAKE', 'stream_CDLHIKKAKEMOD', 'stream_CDLHOMINGPIGEON', 'stream_CDLIDENTICAL3CROWS', 'stream_CDLINNECK', 'stream_CDLINVERTEDHAMMER', 'stream_CDLKICKING', 'stream_CDLKICKINGBYLENGTH', 'stream_CDLLADDERBOTTOM', 'stream_CDLLONGLEGGEDDOJI', 'stream_CDLLONGLINE', 'stream_CDLMARUBOZU', 'stream_CDLMATCHINGLOW', 'stream_CDLMATHOLD', 'stream_CDLMORNINGDOJISTAR', 'stream_CDLMORNINGSTAR', 'stream_CDLONNECK', 'stream_CDLPIERCING', 'stream_CDLRICKSHAWMAN', 'stream_CDLRISEFALL3METHODS', 'stream_CDLSEPARATINGLINES', 'stream_CDLSHOOTINGSTAR', 'stream_CDLSHORTLINE', 'stream_CDLSPINNINGTOP', 'stream_CDLSTALLEDPATTERN', 'stream_CDLSTICKSANDWICH', 'stream_CDLTAKURI', 'stream_CDLTASUKIGAP', 'stream_CDLTHRUSTING', 'stream_CDLTRISTAR', 'stream_CDLUNIQUE3RIVER', 'stream_CDLUPSIDEGAP2CROWS', 'stream_CDLXSIDEGAP3METHODS', 'stream_CEIL', 'stream_CMO', 'stream_CORREL', 'stream_COS', 'stream_COSH', 'stream_DEMA', 'stream_DIV', 'stream_DX', 'stream_EMA', 'stream_EXP', 'stream_FLOOR', 'stream_HT_DCPERIOD', 'stream_HT_DCPHASE', 'stream_HT_PHASOR', 'stream_HT_SINE', 'stream_HT_TRENDLINE', 'stream_HT_TRENDMODE', 'stream_KAMA', 'stream_LINEARREG', 'stream_LINEARREG_ANGLE', 'stream_LINEARREG_INTERCEPT', 'stream_LINEARREG_SLOPE', 'stream_LN', 'stream_LOG10', 'stream_MA', 'stream_MACD', 'stream_MACDEXT', 'stream_MACDFIX', 'stream_MAMA', 'stream_MAVP', 'stream_MAX', 'stream_MAXINDEX', 'stream_MEDPRICE', 'stream_MFI', 'stream_MIDPOINT', 'stream_MIDPRICE', 'stream_MIN', 'stream_MININDEX', 'stream_MINMAX', 'stream_MINMAXINDEX', 'stream_MINUS_DI', 'stream_MINUS_DM', 'stream_MOM', 'stream_MULT', 'stream_NATR', 'stream_OBV', 'stream_PLUS_DI', 'stream_PLUS_DM', 'stream_PPO', 'stream_ROC', 'stream_ROCP', 'stream_ROCR', 'stream_ROCR100', 'stream_RSI', 'stream_SAR', 'stream_SAREXT', 'stream_SIN', 'stream_SINH', 'stream_SMA', 'stream_SQRT', 'stream_STDDEV', 'stream_STOCH', 'stream_STOCHF', 'stream_STOCHRSI', 'stream_SUB', 'stream_SUM', 'stream_T3', 'stream_TAN', 'stream_TANH', 'stream_TEMA', 'stream_TRANGE', 'stream_TRIMA', 'stream_TRIX', 'stream_TSF', 'stream_TYPPRICE', 'stream_ULTOSC', 'stream_VAR', 'stream_WCLPRICE', 'stream_WILLR', 'stream_WMA']
def _wrapper(func):
    ...
def get_function_groups():
    """
    
        Returns a dict with keys of function-group names and values of lists
        of function names ie {'group_names': ['function_names']}
        
    """
def get_functions():
    """
    
        Returns a list of all the functions supported by TALIB
        
    """
MA_Type: _ta_lib.MA_Type  # value = <talib._ta_lib.MA_Type object>
__TA_FUNCTION_NAMES__: list = ['ACOS', 'AD', 'ADD', 'ADOSC', 'ADX', 'ADXR', 'APO', 'AROON', 'AROONOSC', 'ASIN', 'ATAN', 'ATR', 'AVGPRICE', 'BBANDS', 'BETA', 'BOP', 'CCI', 'CDL2CROWS', 'CDL3BLACKCROWS', 'CDL3INSIDE', 'CDL3LINESTRIKE', 'CDL3OUTSIDE', 'CDL3STARSINSOUTH', 'CDL3WHITESOLDIERS', 'CDLABANDONEDBABY', 'CDLADVANCEBLOCK', 'CDLBELTHOLD', 'CDLBREAKAWAY', 'CDLCLOSINGMARUBOZU', 'CDLCONCEALBABYSWALL', 'CDLCOUNTERATTACK', 'CDLDARKCLOUDCOVER', 'CDLDOJI', 'CDLDOJISTAR', 'CDLDRAGONFLYDOJI', 'CDLENGULFING', 'CDLEVENINGDOJISTAR', 'CDLEVENINGSTAR', 'CDLGAPSIDESIDEWHITE', 'CDLGRAVESTONEDOJI', 'CDLHAMMER', 'CDLHANGINGMAN', 'CDLHARAMI', 'CDLHARAMICROSS', 'CDLHIGHWAVE', 'CDLHIKKAKE', 'CDLHIKKAKEMOD', 'CDLHOMINGPIGEON', 'CDLIDENTICAL3CROWS', 'CDLINNECK', 'CDLINVERTEDHAMMER', 'CDLKICKING', 'CDLKICKINGBYLENGTH', 'CDLLADDERBOTTOM', 'CDLLONGLEGGEDDOJI', 'CDLLONGLINE', 'CDLMARUBOZU', 'CDLMATCHINGLOW', 'CDLMATHOLD', 'CDLMORNINGDOJISTAR', 'CDLMORNINGSTAR', 'CDLONNECK', 'CDLPIERCING', 'CDLRICKSHAWMAN', 'CDLRISEFALL3METHODS', 'CDLSEPARATINGLINES', 'CDLSHOOTINGSTAR', 'CDLSHORTLINE', 'CDLSPINNINGTOP', 'CDLSTALLEDPATTERN', 'CDLSTICKSANDWICH', 'CDLTAKURI', 'CDLTASUKIGAP', 'CDLTHRUSTING', 'CDLTRISTAR', 'CDLUNIQUE3RIVER', 'CDLUPSIDEGAP2CROWS', 'CDLXSIDEGAP3METHODS', 'CEIL', 'CMO', 'CORREL', 'COS', 'COSH', 'DEMA', 'DIV', 'DX', 'EMA', 'EXP', 'FLOOR', 'HT_DCPERIOD', 'HT_DCPHASE', 'HT_PHASOR', 'HT_SINE', 'HT_TRENDLINE', 'HT_TRENDMODE', 'KAMA', 'LINEARREG', 'LINEARREG_ANGLE', 'LINEARREG_INTERCEPT', 'LINEARREG_SLOPE', 'LN', 'LOG10', 'MA', 'MACD', 'MACDEXT', 'MACDFIX', 'MAMA', 'MAVP', 'MAX', 'MAXINDEX', 'MEDPRICE', 'MFI', 'MIDPOINT', 'MIDPRICE', 'MIN', 'MININDEX', 'MINMAX', 'MINMAXINDEX', 'MINUS_DI', 'MINUS_DM', 'MOM', 'MULT', 'NATR', 'OBV', 'PLUS_DI', 'PLUS_DM', 'PPO', 'ROC', 'ROCP', 'ROCR', 'ROCR100', 'RSI', 'SAR', 'SAREXT', 'SIN', 'SINH', 'SMA', 'SQRT', 'STDDEV', 'STOCH', 'STOCHF', 'STOCHRSI', 'SUB', 'SUM', 'T3', 'TAN', 'TANH', 'TEMA', 'TRANGE', 'TRIMA', 'TRIX', 'TSF', 'TYPPRICE', 'ULTOSC', 'VAR', 'WCLPRICE', 'WILLR', 'WMA']
__function_groups__: dict = {'Cycle Indicators': ['HT_DCPERIOD', 'HT_DCPHASE', 'HT_PHASOR', 'HT_SINE', 'HT_TRENDMODE'], 'Math Operators': ['ADD', 'DIV', 'MAX', 'MAXINDEX', 'MIN', 'MININDEX', 'MINMAX', 'MINMAXINDEX', 'MULT', 'SUB', 'SUM'], 'Math Transform': ['ACOS', 'ASIN', 'ATAN', 'CEIL', 'COS', 'COSH', 'EXP', 'FLOOR', 'LN', 'LOG10', 'SIN', 'SINH', 'SQRT', 'TAN', 'TANH'], 'Momentum Indicators': ['ADX', 'ADXR', 'APO', 'AROON', 'AROONOSC', 'BOP', 'CCI', 'CMO', 'DX', 'MACD', 'MACDEXT', 'MACDFIX', 'MFI', 'MINUS_DI', 'MINUS_DM', 'MOM', 'PLUS_DI', 'PLUS_DM', 'PPO', 'ROC', 'ROCP', 'ROCR', 'ROCR100', 'RSI', 'STOCH', 'STOCHF', 'STOCHRSI', 'TRIX', 'ULTOSC', 'WILLR'], 'Overlap Studies': ['BBANDS', 'DEMA', 'EMA', 'HT_TRENDLINE', 'KAMA', 'MA', 'MAMA', 'MAVP', 'MIDPOINT', 'MIDPRICE', 'SAR', 'SAREXT', 'SMA', 'T3', 'TEMA', 'TRIMA', 'WMA'], 'Pattern Recognition': ['CDL2CROWS', 'CDL3BLACKCROWS', 'CDL3INSIDE', 'CDL3LINESTRIKE', 'CDL3OUTSIDE', 'CDL3STARSINSOUTH', 'CDL3WHITESOLDIERS', 'CDLABANDONEDBABY', 'CDLADVANCEBLOCK', 'CDLBELTHOLD', 'CDLBREAKAWAY', 'CDLCLOSINGMARUBOZU', 'CDLCONCEALBABYSWALL', 'CDLCOUNTERATTACK', 'CDLDARKCLOUDCOVER', 'CDLDOJI', 'CDLDOJISTAR', 'CDLDRAGONFLYDOJI', 'CDLENGULFING', 'CDLEVENINGDOJISTAR', 'CDLEVENINGSTAR', 'CDLGAPSIDESIDEWHITE', 'CDLGRAVESTONEDOJI', 'CDLHAMMER', 'CDLHANGINGMAN', 'CDLHARAMI', 'CDLHARAMICROSS', 'CDLHIGHWAVE', 'CDLHIKKAKE', 'CDLHIKKAKEMOD', 'CDLHOMINGPIGEON', 'CDLIDENTICAL3CROWS', 'CDLINNECK', 'CDLINVERTEDHAMMER', 'CDLKICKING', 'CDLKICKINGBYLENGTH', 'CDLLADDERBOTTOM', 'CDLLONGLEGGEDDOJI', 'CDLLONGLINE', 'CDLMARUBOZU', 'CDLMATCHINGLOW', 'CDLMATHOLD', 'CDLMORNINGDOJISTAR', 'CDLMORNINGSTAR', 'CDLONNECK', 'CDLPIERCING', 'CDLRICKSHAWMAN', 'CDLRISEFALL3METHODS', 'CDLSEPARATINGLINES', 'CDLSHOOTINGSTAR', 'CDLSHORTLINE', 'CDLSPINNINGTOP', 'CDLSTALLEDPATTERN', 'CDLSTICKSANDWICH', 'CDLTAKURI', 'CDLTASUKIGAP', 'CDLTHRUSTING', 'CDLTRISTAR', 'CDLUNIQUE3RIVER', 'CDLUPSIDEGAP2CROWS', 'CDLXSIDEGAP3METHODS'], 'Price Transform': ['AVGPRICE', 'MEDPRICE', 'TYPPRICE', 'WCLPRICE'], 'Statistic Functions': ['BETA', 'CORREL', 'LINEARREG', 'LINEARREG_ANGLE', 'LINEARREG_INTERCEPT', 'LINEARREG_SLOPE', 'STDDEV', 'TSF', 'VAR'], 'Volatility Indicators': ['ATR', 'NATR', 'TRANGE'], 'Volume Indicators': ['AD', 'ADOSC', 'OBV']}
__ta_version__: bytes  # value = b'0.4.0 (Nov 18 2023 16:34:42)'
__version__: str = '0.4.28'
_pl_Series = None
func_name: str = 'WMA'
stream_func_name: str = 'stream_WMA'
stream_func_names: list = ['stream_ACOS', 'stream_AD', 'stream_ADD', 'stream_ADOSC', 'stream_ADX', 'stream_ADXR', 'stream_APO', 'stream_AROON', 'stream_AROONOSC', 'stream_ASIN', 'stream_ATAN', 'stream_ATR', 'stream_AVGPRICE', 'stream_BBANDS', 'stream_BETA', 'stream_BOP', 'stream_CCI', 'stream_CDL2CROWS', 'stream_CDL3BLACKCROWS', 'stream_CDL3INSIDE', 'stream_CDL3LINESTRIKE', 'stream_CDL3OUTSIDE', 'stream_CDL3STARSINSOUTH', 'stream_CDL3WHITESOLDIERS', 'stream_CDLABANDONEDBABY', 'stream_CDLADVANCEBLOCK', 'stream_CDLBELTHOLD', 'stream_CDLBREAKAWAY', 'stream_CDLCLOSINGMARUBOZU', 'stream_CDLCONCEALBABYSWALL', 'stream_CDLCOUNTERATTACK', 'stream_CDLDARKCLOUDCOVER', 'stream_CDLDOJI', 'stream_CDLDOJISTAR', 'stream_CDLDRAGONFLYDOJI', 'stream_CDLENGULFING', 'stream_CDLEVENINGDOJISTAR', 'stream_CDLEVENINGSTAR', 'stream_CDLGAPSIDESIDEWHITE', 'stream_CDLGRAVESTONEDOJI', 'stream_CDLHAMMER', 'stream_CDLHANGINGMAN', 'stream_CDLHARAMI', 'stream_CDLHARAMICROSS', 'stream_CDLHIGHWAVE', 'stream_CDLHIKKAKE', 'stream_CDLHIKKAKEMOD', 'stream_CDLHOMINGPIGEON', 'stream_CDLIDENTICAL3CROWS', 'stream_CDLINNECK', 'stream_CDLINVERTEDHAMMER', 'stream_CDLKICKING', 'stream_CDLKICKINGBYLENGTH', 'stream_CDLLADDERBOTTOM', 'stream_CDLLONGLEGGEDDOJI', 'stream_CDLLONGLINE', 'stream_CDLMARUBOZU', 'stream_CDLMATCHINGLOW', 'stream_CDLMATHOLD', 'stream_CDLMORNINGDOJISTAR', 'stream_CDLMORNINGSTAR', 'stream_CDLONNECK', 'stream_CDLPIERCING', 'stream_CDLRICKSHAWMAN', 'stream_CDLRISEFALL3METHODS', 'stream_CDLSEPARATINGLINES', 'stream_CDLSHOOTINGSTAR', 'stream_CDLSHORTLINE', 'stream_CDLSPINNINGTOP', 'stream_CDLSTALLEDPATTERN', 'stream_CDLSTICKSANDWICH', 'stream_CDLTAKURI', 'stream_CDLTASUKIGAP', 'stream_CDLTHRUSTING', 'stream_CDLTRISTAR', 'stream_CDLUNIQUE3RIVER', 'stream_CDLUPSIDEGAP2CROWS', 'stream_CDLXSIDEGAP3METHODS', 'stream_CEIL', 'stream_CMO', 'stream_CORREL', 'stream_COS', 'stream_COSH', 'stream_DEMA', 'stream_DIV', 'stream_DX', 'stream_EMA', 'stream_EXP', 'stream_FLOOR', 'stream_HT_DCPERIOD', 'stream_HT_DCPHASE', 'stream_HT_PHASOR', 'stream_HT_SINE', 'stream_HT_TRENDLINE', 'stream_HT_TRENDMODE', 'stream_KAMA', 'stream_LINEARREG', 'stream_LINEARREG_ANGLE', 'stream_LINEARREG_INTERCEPT', 'stream_LINEARREG_SLOPE', 'stream_LN', 'stream_LOG10', 'stream_MA', 'stream_MACD', 'stream_MACDEXT', 'stream_MACDFIX', 'stream_MAMA', 'stream_MAVP', 'stream_MAX', 'stream_MAXINDEX', 'stream_MEDPRICE', 'stream_MFI', 'stream_MIDPOINT', 'stream_MIDPRICE', 'stream_MIN', 'stream_MININDEX', 'stream_MINMAX', 'stream_MINMAXINDEX', 'stream_MINUS_DI', 'stream_MINUS_DM', 'stream_MOM', 'stream_MULT', 'stream_NATR', 'stream_OBV', 'stream_PLUS_DI', 'stream_PLUS_DM', 'stream_PPO', 'stream_ROC', 'stream_ROCP', 'stream_ROCR', 'stream_ROCR100', 'stream_RSI', 'stream_SAR', 'stream_SAREXT', 'stream_SIN', 'stream_SINH', 'stream_SMA', 'stream_SQRT', 'stream_STDDEV', 'stream_STOCH', 'stream_STOCHF', 'stream_STOCHRSI', 'stream_SUB', 'stream_SUM', 'stream_T3', 'stream_TAN', 'stream_TANH', 'stream_TEMA', 'stream_TRANGE', 'stream_TRIMA', 'stream_TRIX', 'stream_TSF', 'stream_TYPPRICE', 'stream_ULTOSC', 'stream_VAR', 'stream_WCLPRICE', 'stream_WILLR', 'stream_WMA']
func = _ta_lib
