from __future__ import annotations
from talib import _ta_lib
from talib._ta_lib import stream_ACOS as ACOS
from talib._ta_lib import stream_AD as AD
from talib._ta_lib import stream_ADD as ADD
from talib._ta_lib import stream_ADOSC as ADOSC
from talib._ta_lib import stream_ADX as ADX
from talib._ta_lib import stream_ADXR as ADXR
from talib._ta_lib import stream_APO as APO
from talib._ta_lib import stream_AROON as AROON
from talib._ta_lib import stream_AROONOSC as AROONOSC
from talib._ta_lib import stream_ASIN as ASIN
from talib._ta_lib import stream_ATAN as ATAN
from talib._ta_lib import stream_ATR as ATR
from talib._ta_lib import stream_AVGPRICE as AVGPRICE
from talib._ta_lib import stream_BBANDS as BBANDS
from talib._ta_lib import stream_BETA as BETA
from talib._ta_lib import stream_BOP as BOP
from talib._ta_lib import stream_CCI as CCI
from talib._ta_lib import stream_CDL2CROWS as CDL2CROWS
from talib._ta_lib import stream_CDL3BLACKCROWS as CDL3BLACKCROWS
from talib._ta_lib import stream_CDL3INSIDE as CDL3INSIDE
from talib._ta_lib import stream_CDL3LINESTRIKE as CDL3LINESTRIKE
from talib._ta_lib import stream_CDL3OUTSIDE as CDL3OUTSIDE
from talib._ta_lib import stream_CDL3STARSINSOUTH as CDL3STARSINSOUTH
from talib._ta_lib import stream_CDL3WHITESOLDIERS as CDL3WHITESOLDIERS
from talib._ta_lib import stream_CDLABANDONEDBABY as CDLABANDONEDBABY
from talib._ta_lib import stream_CDLADVANCEBLOCK as CDLADVANCEBLOCK
from talib._ta_lib import stream_CDLBELTHOLD as CDLBELTHOLD
from talib._ta_lib import stream_CDLBREAKAWAY as CDLBREAKAWAY
from talib._ta_lib import stream_CDLCLOSINGMARUBOZU as CDLCLOSINGMARUBOZU
from talib._ta_lib import stream_CDLCONCEALBABYSWALL as CDLCONCEALBABYSWALL
from talib._ta_lib import stream_CDLCOUNTERATTACK as CDLCOUNTERATTACK
from talib._ta_lib import stream_CDLDARKCLOUDCOVER as CDLDARKCLOUDCOVER
from talib._ta_lib import stream_CDLDOJI as CDLDOJI
from talib._ta_lib import stream_CDLDOJISTAR as CDLDOJISTAR
from talib._ta_lib import stream_CDLDRAGONFLYDOJI as CDLDRAGONFLYDOJI
from talib._ta_lib import stream_CDLENGULFING as CDLENGULFING
from talib._ta_lib import stream_CDLEVENINGDOJISTAR as CDLEVENINGDOJISTAR
from talib._ta_lib import stream_CDLEVENINGSTAR as CDLEVENINGSTAR
from talib._ta_lib import stream_CDLGAPSIDESIDEWHITE as CDLGAPSIDESIDEWHITE
from talib._ta_lib import stream_CDLGRAVESTONEDOJI as CDLGRAVESTONEDOJI
from talib._ta_lib import stream_CDLHAMMER as CDLHAMMER
from talib._ta_lib import stream_CDLHANGINGMAN as CDLHANGINGMAN
from talib._ta_lib import stream_CDLHARAMI as CDLHARAMI
from talib._ta_lib import stream_CDLHARAMICROSS as CDLHARAMICROSS
from talib._ta_lib import stream_CDLHIGHWAVE as CDLHIGHWAVE
from talib._ta_lib import stream_CDLHIKKAKE as CDLHIKKAKE
from talib._ta_lib import stream_CDLHIKKAKEMOD as CDLHIKKAKEMOD
from talib._ta_lib import stream_CDLHOMINGPIGEON as CDLHOMINGPIGEON
from talib._ta_lib import stream_CDLIDENTICAL3CROWS as CDLIDENTICAL3CROWS
from talib._ta_lib import stream_CDLINNECK as CDLINNECK
from talib._ta_lib import stream_CDLINVERTEDHAMMER as CDLINVERTEDHAMMER
from talib._ta_lib import stream_CDLKICKING as CDLKICKING
from talib._ta_lib import stream_CDLKICKINGBYLENGTH as CDLKICKINGBYLENGTH
from talib._ta_lib import stream_CDLLADDERBOTTOM as CDLLADDERBOTTOM
from talib._ta_lib import stream_CDLLONGLEGGEDDOJI as CDLLONGLEGGEDDOJI
from talib._ta_lib import stream_CDLLONGLINE as CDLLONGLINE
from talib._ta_lib import stream_CDLMARUBOZU as CDLMARUBOZU
from talib._ta_lib import stream_CDLMATCHINGLOW as CDLMATCHINGLOW
from talib._ta_lib import stream_CDLMATHOLD as CDLMATHOLD
from talib._ta_lib import stream_CDLMORNINGDOJISTAR as CDLMORNINGDOJISTAR
from talib._ta_lib import stream_CDLMORNINGSTAR as CDLMORNINGSTAR
from talib._ta_lib import stream_CDLONNECK as CDLONNECK
from talib._ta_lib import stream_CDLPIERCING as CDLPIERCING
from talib._ta_lib import stream_CDLRICKSHAWMAN as CDLRICKSHAWMAN
from talib._ta_lib import stream_CDLRISEFALL3METHODS as CDLRISEFALL3METHODS
from talib._ta_lib import stream_CDLSEPARATINGLINES as CDLSEPARATINGLINES
from talib._ta_lib import stream_CDLSHOOTINGSTAR as CDLSHOOTINGSTAR
from talib._ta_lib import stream_CDLSHORTLINE as CDLSHORTLINE
from talib._ta_lib import stream_CDLSPINNINGTOP as CDLSPINNINGTOP
from talib._ta_lib import stream_CDLSTALLEDPATTERN as CDLSTALLEDPATTERN
from talib._ta_lib import stream_CDLSTICKSANDWICH as CDLSTICKSANDWICH
from talib._ta_lib import stream_CDLTAKURI as CDLTAKURI
from talib._ta_lib import stream_CDLTASUKIGAP as CDLTASUKIGAP
from talib._ta_lib import stream_CDLTHRUSTING as CDLTHRUSTING
from talib._ta_lib import stream_CDLTRISTAR as CDLTRISTAR
from talib._ta_lib import stream_CDLUNIQUE3RIVER as CDLUNIQUE3RIVER
from talib._ta_lib import stream_CDLUPSIDEGAP2CROWS as CDLUPSIDEGAP2CROWS
from talib._ta_lib import stream_CDLXSIDEGAP3METHODS as CDLXSIDEGAP3METHODS
from talib._ta_lib import stream_CEIL as CEIL
from talib._ta_lib import stream_CMO as CMO
from talib._ta_lib import stream_CORREL as CORREL
from talib._ta_lib import stream_COS as COS
from talib._ta_lib import stream_COSH as COSH
from talib._ta_lib import stream_DEMA as DEMA
from talib._ta_lib import stream_DIV as DIV
from talib._ta_lib import stream_DX as DX
from talib._ta_lib import stream_EMA as EMA
from talib._ta_lib import stream_EXP as EXP
from talib._ta_lib import stream_FLOOR as FLOOR
from talib._ta_lib import stream_HT_DCPERIOD as HT_DCPERIOD
from talib._ta_lib import stream_HT_DCPHASE as HT_DCPHASE
from talib._ta_lib import stream_HT_PHASOR as HT_PHASOR
from talib._ta_lib import stream_HT_SINE as HT_SINE
from talib._ta_lib import stream_HT_TRENDLINE as HT_TRENDLINE
from talib._ta_lib import stream_HT_TRENDMODE as HT_TRENDMODE
from talib._ta_lib import stream_KAMA as KAMA
from talib._ta_lib import stream_LINEARREG as LINEARREG
from talib._ta_lib import stream_LINEARREG_ANGLE as LINEARREG_ANGLE
from talib._ta_lib import stream_LINEARREG_INTERCEPT as LINEARREG_INTERCEPT
from talib._ta_lib import stream_LINEARREG_SLOPE as LINEARREG_SLOPE
from talib._ta_lib import stream_LN as LN
from talib._ta_lib import stream_LOG10 as LOG10
from talib._ta_lib import stream_MA as MA
from talib._ta_lib import stream_MACD as MACD
from talib._ta_lib import stream_MACDEXT as MACDEXT
from talib._ta_lib import stream_MACDFIX as MACDFIX
from talib._ta_lib import stream_MAMA as MAMA
from talib._ta_lib import stream_MAVP as MAVP
from talib._ta_lib import stream_MAX as MAX
from talib._ta_lib import stream_MAXINDEX as MAXINDEX
from talib._ta_lib import stream_MEDPRICE as MEDPRICE
from talib._ta_lib import stream_MFI as MFI
from talib._ta_lib import stream_MIDPOINT as MIDPOINT
from talib._ta_lib import stream_MIDPRICE as MIDPRICE
from talib._ta_lib import stream_MIN as MIN
from talib._ta_lib import stream_MININDEX as MININDEX
from talib._ta_lib import stream_MINMAX as MINMAX
from talib._ta_lib import stream_MINMAXINDEX as MINMAXINDEX
from talib._ta_lib import stream_MINUS_DI as MINUS_DI
from talib._ta_lib import stream_MINUS_DM as MINUS_DM
from talib._ta_lib import stream_MOM as MOM
from talib._ta_lib import stream_MULT as MULT
from talib._ta_lib import stream_NATR as NATR
from talib._ta_lib import stream_OBV as OBV
from talib._ta_lib import stream_PLUS_DI as PLUS_DI
from talib._ta_lib import stream_PLUS_DM as PLUS_DM
from talib._ta_lib import stream_PPO as PPO
from talib._ta_lib import stream_ROC as ROC
from talib._ta_lib import stream_ROCP as ROCP
from talib._ta_lib import stream_ROCR as ROCR
from talib._ta_lib import stream_ROCR100 as ROCR100
from talib._ta_lib import stream_RSI as RSI
from talib._ta_lib import stream_SAR as SAR
from talib._ta_lib import stream_SAREXT as SAREXT
from talib._ta_lib import stream_SIN as SIN
from talib._ta_lib import stream_SINH as SINH
from talib._ta_lib import stream_SMA as SMA
from talib._ta_lib import stream_SQRT as SQRT
from talib._ta_lib import stream_STDDEV as STDDEV
from talib._ta_lib import stream_STOCH as STOCH
from talib._ta_lib import stream_STOCHF as STOCHF
from talib._ta_lib import stream_STOCHRSI as STOCHRSI
from talib._ta_lib import stream_SUB as SUB
from talib._ta_lib import stream_SUM as SUM
from talib._ta_lib import stream_T3 as T3
from talib._ta_lib import stream_TAN as TAN
from talib._ta_lib import stream_TANH as TANH
from talib._ta_lib import stream_TEMA as TEMA
from talib._ta_lib import stream_TRANGE as TRANGE
from talib._ta_lib import stream_TRIMA as TRIMA
from talib._ta_lib import stream_TRIX as TRIX
from talib._ta_lib import stream_TSF as TSF
from talib._ta_lib import stream_TYPPRICE as TYPPRICE
from talib._ta_lib import stream_ULTOSC as ULTOSC
from talib._ta_lib import stream_VAR as VAR
from talib._ta_lib import stream_WCLPRICE as WCLPRICE
from talib._ta_lib import stream_WILLR as WILLR
from talib._ta_lib import stream_WMA as WMA
__all__ = ['ACOS', 'AD', 'ADD', 'ADOSC', 'ADX', 'ADXR', 'APO', 'AROON', 'AROONOSC', 'ASIN', 'ATAN', 'ATR', 'AVGPRICE', 'BBANDS', 'BETA', 'BOP', 'CCI', 'CDL2CROWS', 'CDL3BLACKCROWS', 'CDL3INSIDE', 'CDL3LINESTRIKE', 'CDL3OUTSIDE', 'CDL3STARSINSOUTH', 'CDL3WHITESOLDIERS', 'CDLABANDONEDBABY', 'CDLADVANCEBLOCK', 'CDLBELTHOLD', 'CDLBREAKAWAY', 'CDLCLOSINGMARUBOZU', 'CDLCONCEALBABYSWALL', 'CDLCOUNTERATTACK', 'CDLDARKCLOUDCOVER', 'CDLDOJI', 'CDLDOJISTAR', 'CDLDRAGONFLYDOJI', 'CDLENGULFING', 'CDLEVENINGDOJISTAR', 'CDLEVENINGSTAR', 'CDLGAPSIDESIDEWHITE', 'CDLGRAVESTONEDOJI', 'CDLHAMMER', 'CDLHANGINGMAN', 'CDLHARAMI', 'CDLHARAMICROSS', 'CDLHIGHWAVE', 'CDLHIKKAKE', 'CDLHIKKAKEMOD', 'CDLHOMINGPIGEON', 'CDLIDENTICAL3CROWS', 'CDLINNECK', 'CDLINVERTEDHAMMER', 'CDLKICKING', 'CDLKICKINGBYLENGTH', 'CDLLADDERBOTTOM', 'CDLLONGLEGGEDDOJI', 'CDLLONGLINE', 'CDLMARUBOZU', 'CDLMATCHINGLOW', 'CDLMATHOLD', 'CDLMORNINGDOJISTAR', 'CDLMORNINGSTAR', 'CDLONNECK', 'CDLPIERCING', 'CDLRICKSHAWMAN', 'CDLRISEFALL3METHODS', 'CDLSEPARATINGLINES', 'CDLSHOOTINGSTAR', 'CDLSHORTLINE', 'CDLSPINNINGTOP', 'CDLSTALLEDPATTERN', 'CDLSTICKSANDWICH', 'CDLTAKURI', 'CDLTASUKIGAP', 'CDLTHRUSTING', 'CDLTRISTAR', 'CDLUNIQUE3RIVER', 'CDLUPSIDEGAP2CROWS', 'CDLXSIDEGAP3METHODS', 'CEIL', 'CMO', 'CORREL', 'COS', 'COSH', 'DEMA', 'DIV', 'DX', 'EMA', 'EXP', 'FLOOR', 'HT_DCPERIOD', 'HT_DCPHASE', 'HT_PHASOR', 'HT_SINE', 'HT_TRENDLINE', 'HT_TRENDMODE', 'KAMA', 'LINEARREG', 'LINEARREG_ANGLE', 'LINEARREG_INTERCEPT', 'LINEARREG_SLOPE', 'LN', 'LOG10', 'MA', 'MACD', 'MACDEXT', 'MACDFIX', 'MAMA', 'MAVP', 'MAX', 'MAXINDEX', 'MEDPRICE', 'MFI', 'MIDPOINT', 'MIDPRICE', 'MIN', 'MININDEX', 'MINMAX', 'MINMAXINDEX', 'MINUS_DI', 'MINUS_DM', 'MOM', 'MULT', 'NATR', 'OBV', 'PLUS_DI', 'PLUS_DM', 'PPO', 'ROC', 'ROCP', 'ROCR', 'ROCR100', 'RSI', 'SAR', 'SAREXT', 'SIN', 'SINH', 'SMA', 'SQRT', 'STDDEV', 'STOCH', 'STOCHF', 'STOCHRSI', 'SUB', 'SUM', 'T3', 'TAN', 'TANH', 'TEMA', 'TRANGE', 'TRIMA', 'TRIX', 'TSF', 'TYPPRICE', 'ULTOSC', 'VAR', 'WCLPRICE', 'WILLR', 'WMA', 'func_name']
__TA_FUNCTION_NAMES__: list = ['ACOS', 'AD', 'ADD', 'ADOSC', 'ADX', 'ADXR', 'APO', 'AROON', 'AROONOSC', 'ASIN', 'ATAN', 'ATR', 'AVGPRICE', 'BBANDS', 'BETA', 'BOP', 'CCI', 'CDL2CROWS', 'CDL3BLACKCROWS', 'CDL3INSIDE', 'CDL3LINESTRIKE', 'CDL3OUTSIDE', 'CDL3STARSINSOUTH', 'CDL3WHITESOLDIERS', 'CDLABANDONEDBABY', 'CDLADVANCEBLOCK', 'CDLBELTHOLD', 'CDLBREAKAWAY', 'CDLCLOSINGMARUBOZU', 'CDLCONCEALBABYSWALL', 'CDLCOUNTERATTACK', 'CDLDARKCLOUDCOVER', 'CDLDOJI', 'CDLDOJISTAR', 'CDLDRAGONFLYDOJI', 'CDLENGULFING', 'CDLEVENINGDOJISTAR', 'CDLEVENINGSTAR', 'CDLGAPSIDESIDEWHITE', 'CDLGRAVESTONEDOJI', 'CDLHAMMER', 'CDLHANGINGMAN', 'CDLHARAMI', 'CDLHARAMICROSS', 'CDLHIGHWAVE', 'CDLHIKKAKE', 'CDLHIKKAKEMOD', 'CDLHOMINGPIGEON', 'CDLIDENTICAL3CROWS', 'CDLINNECK', 'CDLINVERTEDHAMMER', 'CDLKICKING', 'CDLKICKINGBYLENGTH', 'CDLLADDERBOTTOM', 'CDLLONGLEGGEDDOJI', 'CDLLONGLINE', 'CDLMARUBOZU', 'CDLMATCHINGLOW', 'CDLMATHOLD', 'CDLMORNINGDOJISTAR', 'CDLMORNINGSTAR', 'CDLONNECK', 'CDLPIERCING', 'CDLRICKSHAWMAN', 'CDLRISEFALL3METHODS', 'CDLSEPARATINGLINES', 'CDLSHOOTINGSTAR', 'CDLSHORTLINE', 'CDLSPINNINGTOP', 'CDLSTALLEDPATTERN', 'CDLSTICKSANDWICH', 'CDLTAKURI', 'CDLTASUKIGAP', 'CDLTHRUSTING', 'CDLTRISTAR', 'CDLUNIQUE3RIVER', 'CDLUPSIDEGAP2CROWS', 'CDLXSIDEGAP3METHODS', 'CEIL', 'CMO', 'CORREL', 'COS', 'COSH', 'DEMA', 'DIV', 'DX', 'EMA', 'EXP', 'FLOOR', 'HT_DCPERIOD', 'HT_DCPHASE', 'HT_PHASOR', 'HT_SINE', 'HT_TRENDLINE', 'HT_TRENDMODE', 'KAMA', 'LINEARREG', 'LINEARREG_ANGLE', 'LINEARREG_INTERCEPT', 'LINEARREG_SLOPE', 'LN', 'LOG10', 'MA', 'MACD', 'MACDEXT', 'MACDFIX', 'MAMA', 'MAVP', 'MAX', 'MAXINDEX', 'MEDPRICE', 'MFI', 'MIDPOINT', 'MIDPRICE', 'MIN', 'MININDEX', 'MINMAX', 'MINMAXINDEX', 'MINUS_DI', 'MINUS_DM', 'MOM', 'MULT', 'NATR', 'OBV', 'PLUS_DI', 'PLUS_DM', 'PPO', 'ROC', 'ROCP', 'ROCR', 'ROCR100', 'RSI', 'SAR', 'SAREXT', 'SIN', 'SINH', 'SMA', 'SQRT', 'STDDEV', 'STOCH', 'STOCHF', 'STOCHRSI', 'SUB', 'SUM', 'T3', 'TAN', 'TANH', 'TEMA', 'TRANGE', 'TRIMA', 'TRIX', 'TSF', 'TYPPRICE', 'ULTOSC', 'VAR', 'WCLPRICE', 'WILLR', 'WMA']
func_name: str = 'WMA'
