# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tdx_tools/protos/bar.proto
# Protobuf Python Version: 4.26.0-dev
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atdx_tools/protos/bar.proto\"\x8b\x01\n\x03\x42\x61r\x12\x0e\n\x06market\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04open\x18\x03 \x01(\x02\x12\r\n\x05\x63lose\x18\x04 \x01(\x02\x12\x0c\n\x04high\x18\x05 \x01(\x02\x12\x0b\n\x03low\x18\x06 \x01(\x02\x12\x0b\n\x03vol\x18\x07 \x01(\x02\x12\x0e\n\x06\x61mount\x18\x08 \x01(\x02\x12\x11\n\ttimestamp\x18\t \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tdx_tools.protos.bar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._loaded_options = None
  _globals['_BAR']._serialized_start=31
  _globals['_BAR']._serialized_end=170
# @@protoc_insertion_point(module_scope)
