"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Stock(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    MARKET_FIELD_NUMBER: builtins.int
    FULL_NAME_FIELD_NUMBER: builtins.int
    BIRTH_DATE_FIELD_NUMBER: builtins.int
    code: typing.Text
    name: typing.Text
    market: typing.Text
    full_name: typing.Text
    birth_date: typing.Text
    def __init__(self,
        *,
        code: typing.Text = ...,
        name: typing.Text = ...,
        market: typing.Text = ...,
        full_name: typing.Text = ...,
        birth_date: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["birth_date",b"birth_date","code",b"code","full_name",b"full_name","market",b"market","name",b"name"]) -> None: ...
global___Stock = Stock
