"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class XRXD(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    MARKET_FIELD_NUMBER: builtins.int
    DATE_TS_FIELD_NUMBER: builtins.int
    code: typing.Text
    name: typing.Text
    market: typing.Text
    date_ts: builtins.float
    """除权除息日  unix timestamp"""

    def __init__(self,
        *,
        code: typing.Text = ...,
        name: typing.Text = ...,
        market: typing.Text = ...,
        date_ts: builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","date_ts",b"date_ts","market",b"market","name",b"name"]) -> None: ...
global___XRXD = XRXD
